version: '3'

services:
  php-ngx:
    build:
      context: .
      dockerfile: php-ngx.dockerfile
    ports:
      - "9801:9801"

  php-cli:
    build:
      context: .
      dockerfile: php-cli.dockerfile
    ports:
      - "9802:9802"

  php-fpm:
    build:
      context: .
      dockerfile: php-fpm.dockerfile
    ports:
      - "9803:9803"

  swoole:
    build:
      context: .
      dockerfile: php-swoole.dockerfile
    ports:
      - "9804:9804"

  frankenphp-worker:
    build:
      context: .
      dockerfile: frankenphp-worker.dockerfile
    ports:
      - "9805:9805"

  frankenphp-cgi:
    build:
      context: .
      dockerfile: frankenphp-cgi.dockerfile
    ports:
      - "9806:80"
    environment:
      SERVER_NAME: ":80"

  roadrunner:
    build:
      context: .
      dockerfile: roadrunner.dockerfile
    ports:
      - "9807:9807"
